sftmime.exe delete APP:"CRIS Clyde Live 5.0.220.3" /LOG "%tmp%/CRIS.log"
sftmime.exe delete APP:"CRIS V2.09.10 2.09.10e"  /LOG "%tmp%/CRIS.log"
sftmime.exe delete APP:"CRIS Clyde 5.0.220.3"  /LOG "%tmp%/CRIS.log"
sftmime.exe delete APP:"CRIS-IRH 5.0.220.3"  /LOG "%tmp%/CRIS.log"
sftmime.exe delete APP:"CRIS 3 - RAH 6.0.210.7"  /LOG "%tmp%/CRIS.log"
sftmime.exe delete APP:"CRIS - Clyde 6.0.210.7"  /LOG "%tmp%/CRIS.log"
sftmime.exe delete APP:"CRIS Live System v2 5.2.220.3"  /LOG "%tmp%/CRIS.log"
sftmime.exe delete APP:"CRIS Live System 5.0.220.3"  /LOG "%tmp%/CRIS.log"
sftmime.exe delete APP:"CRIS Train 1.1"  /LOG "%tmp%/CRIS.log"
sftmime.exe delete APP:"CRIS 2.09.10"  /LOG "%tmp%/CRIS.log"
sftmime.exe delete APP:"CRIS 2.09.11" /LOG "%tmp%/CRIS.log"
